// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/recommender.proto

package edu.beuth.movies.services.recommender.pb;

public interface RecommendMoviesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.RecommendMoviesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string reference_movies = 1;</code>
   */
  java.util.List<java.lang.String>
      getReferenceMoviesList();
  /**
   * <code>repeated string reference_movies = 1;</code>
   */
  int getReferenceMoviesCount();
  /**
   * <code>repeated string reference_movies = 1;</code>
   */
  java.lang.String getReferenceMovies(int index);
  /**
   * <code>repeated string reference_movies = 1;</code>
   */
  com.google.protobuf.ByteString
      getReferenceMoviesBytes(int index);
}
