// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/recommender.proto

package edu.beuth.movies.services.recommender.pb;

/**
 * Protobuf type {@code pb.RecommendMoviesResponse}
 */
public  final class RecommendMoviesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.RecommendMoviesResponse)
    RecommendMoviesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecommendMoviesResponse.newBuilder() to construct.
  private RecommendMoviesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecommendMoviesResponse() {
    recommendedMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RecommendMoviesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              recommendedMovies_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            recommendedMovies_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        recommendedMovies_ = recommendedMovies_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.beuth.movies.services.recommender.pb.Recommender.internal_static_pb_RecommendMoviesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.beuth.movies.services.recommender.pb.Recommender.internal_static_pb_RecommendMoviesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse.class, edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse.Builder.class);
  }

  public static final int RECOMMENDED_MOVIES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList recommendedMovies_;
  /**
   * <code>repeated string recommended_movies = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getRecommendedMoviesList() {
    return recommendedMovies_;
  }
  /**
   * <code>repeated string recommended_movies = 1;</code>
   */
  public int getRecommendedMoviesCount() {
    return recommendedMovies_.size();
  }
  /**
   * <code>repeated string recommended_movies = 1;</code>
   */
  public java.lang.String getRecommendedMovies(int index) {
    return recommendedMovies_.get(index);
  }
  /**
   * <code>repeated string recommended_movies = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRecommendedMoviesBytes(int index) {
    return recommendedMovies_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < recommendedMovies_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, recommendedMovies_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < recommendedMovies_.size(); i++) {
        dataSize += computeStringSizeNoTag(recommendedMovies_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRecommendedMoviesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse)) {
      return super.equals(obj);
    }
    edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse other = (edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse) obj;

    boolean result = true;
    result = result && getRecommendedMoviesList()
        .equals(other.getRecommendedMoviesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRecommendedMoviesCount() > 0) {
      hash = (37 * hash) + RECOMMENDED_MOVIES_FIELD_NUMBER;
      hash = (53 * hash) + getRecommendedMoviesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.RecommendMoviesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.RecommendMoviesResponse)
      edu.beuth.movies.services.recommender.pb.RecommendMoviesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.beuth.movies.services.recommender.pb.Recommender.internal_static_pb_RecommendMoviesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.beuth.movies.services.recommender.pb.Recommender.internal_static_pb_RecommendMoviesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse.class, edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse.Builder.class);
    }

    // Construct using edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      recommendedMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.beuth.movies.services.recommender.pb.Recommender.internal_static_pb_RecommendMoviesResponse_descriptor;
    }

    @java.lang.Override
    public edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse getDefaultInstanceForType() {
      return edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse build() {
      edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse buildPartial() {
      edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse result = new edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        recommendedMovies_ = recommendedMovies_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.recommendedMovies_ = recommendedMovies_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse) {
        return mergeFrom((edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse other) {
      if (other == edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse.getDefaultInstance()) return this;
      if (!other.recommendedMovies_.isEmpty()) {
        if (recommendedMovies_.isEmpty()) {
          recommendedMovies_ = other.recommendedMovies_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRecommendedMoviesIsMutable();
          recommendedMovies_.addAll(other.recommendedMovies_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList recommendedMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRecommendedMoviesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        recommendedMovies_ = new com.google.protobuf.LazyStringArrayList(recommendedMovies_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRecommendedMoviesList() {
      return recommendedMovies_.getUnmodifiableView();
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public int getRecommendedMoviesCount() {
      return recommendedMovies_.size();
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public java.lang.String getRecommendedMovies(int index) {
      return recommendedMovies_.get(index);
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRecommendedMoviesBytes(int index) {
      return recommendedMovies_.getByteString(index);
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public Builder setRecommendedMovies(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRecommendedMoviesIsMutable();
      recommendedMovies_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public Builder addRecommendedMovies(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRecommendedMoviesIsMutable();
      recommendedMovies_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public Builder addAllRecommendedMovies(
        java.lang.Iterable<java.lang.String> values) {
      ensureRecommendedMoviesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, recommendedMovies_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public Builder clearRecommendedMovies() {
      recommendedMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public Builder addRecommendedMoviesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRecommendedMoviesIsMutable();
      recommendedMovies_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.RecommendMoviesResponse)
  }

  // @@protoc_insertion_point(class_scope:pb.RecommendMoviesResponse)
  private static final edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse();
  }

  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecommendMoviesResponse>
      PARSER = new com.google.protobuf.AbstractParser<RecommendMoviesResponse>() {
    @java.lang.Override
    public RecommendMoviesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RecommendMoviesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RecommendMoviesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecommendMoviesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.beuth.movies.services.recommender.pb.RecommendMoviesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

