// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/recommender.proto

package edu.beuth.movies.services.recommender.pb;

public interface RecommendMoviesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.RecommendMoviesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string recommended_movies = 1;</code>
   */
  java.util.List<java.lang.String>
      getRecommendedMoviesList();
  /**
   * <code>repeated string recommended_movies = 1;</code>
   */
  int getRecommendedMoviesCount();
  /**
   * <code>repeated string recommended_movies = 1;</code>
   */
  java.lang.String getRecommendedMovies(int index);
  /**
   * <code>repeated string recommended_movies = 1;</code>
   */
  com.google.protobuf.ByteString
      getRecommendedMoviesBytes(int index);
}
