# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import recommender_pb2 as grpc_dot_recommender__pb2


class MovieRecommenderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.recommend_movies = channel.unary_unary(
        '/pb.MovieRecommender/recommend_movies',
        request_serializer=grpc_dot_recommender__pb2.RecommendMoviesRequest.SerializeToString,
        response_deserializer=grpc_dot_recommender__pb2.RecommendMoviesResponse.FromString,
        )


class MovieRecommenderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def recommend_movies(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MovieRecommenderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'recommend_movies': grpc.unary_unary_rpc_method_handler(
          servicer.recommend_movies,
          request_deserializer=grpc_dot_recommender__pb2.RecommendMoviesRequest.FromString,
          response_serializer=grpc_dot_recommender__pb2.RecommendMoviesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.MovieRecommender', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
