// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/recommender.proto

package edu.beuth.movies.services.recommender.pb;

public final class Recommender {
  private Recommender() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_RecommendMoviesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_RecommendMoviesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_RecommendMoviesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_RecommendMoviesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024pb/recommender.proto\022\002pb\"2\n\026RecommendM" +
      "oviesRequest\022\030\n\020reference_movies\030\001 \003(\t\"5" +
      "\n\027RecommendMoviesResponse\022\032\n\022recommended" +
      "_movies\030\001 \003(\t2_\n\020MovieRecommender\022K\n\020rec" +
      "ommend_movies\022\032.pb.RecommendMoviesReques" +
      "t\032\033.pb.RecommendMoviesResponseB,\n(edu.be" +
      "uth.movies.services.recommender.pbP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_RecommendMoviesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_RecommendMoviesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_RecommendMoviesRequest_descriptor,
        new java.lang.String[] { "ReferenceMovies", });
    internal_static_pb_RecommendMoviesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_RecommendMoviesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_RecommendMoviesResponse_descriptor,
        new java.lang.String[] { "RecommendedMovies", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
