// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/recommender.proto

package edu.beuth.movies.services.recommender.pb;

public final class Recommender {
  private Recommender() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecommendMoviesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RecommendMoviesRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    java.util.List<java.lang.String>
        getReferenceMoviesList();
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    int getReferenceMoviesCount();
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    java.lang.String getReferenceMovies(int index);
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    com.google.protobuf.ByteString
        getReferenceMoviesBytes(int index);
  }
  /**
   * Protobuf type {@code RecommendMoviesRequest}
   */
  public  static final class RecommendMoviesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RecommendMoviesRequest)
      RecommendMoviesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecommendMoviesRequest.newBuilder() to construct.
    private RecommendMoviesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecommendMoviesRequest() {
      referenceMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecommendMoviesRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                referenceMovies_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              referenceMovies_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          referenceMovies_ = referenceMovies_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Recommender.internal_static_pb_RecommendMoviesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Recommender.internal_static_pb_RecommendMoviesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Recommender.RecommendMoviesRequest.class, Recommender.RecommendMoviesRequest.Builder.class);
    }

    public static final int REFERENCE_MOVIES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList referenceMovies_;
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getReferenceMoviesList() {
      return referenceMovies_;
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public int getReferenceMoviesCount() {
      return referenceMovies_.size();
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public java.lang.String getReferenceMovies(int index) {
      return referenceMovies_.get(index);
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReferenceMoviesBytes(int index) {
      return referenceMovies_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < referenceMovies_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, referenceMovies_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < referenceMovies_.size(); i++) {
          dataSize += computeStringSizeNoTag(referenceMovies_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getReferenceMoviesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Recommender.RecommendMoviesRequest)) {
        return super.equals(obj);
      }
      Recommender.RecommendMoviesRequest other = (Recommender.RecommendMoviesRequest) obj;

      boolean result = true;
      result = result && getReferenceMoviesList()
          .equals(other.getReferenceMoviesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getReferenceMoviesCount() > 0) {
        hash = (37 * hash) + REFERENCE_MOVIES_FIELD_NUMBER;
        hash = (53 * hash) + getReferenceMoviesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Recommender.RecommendMoviesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Recommender.RecommendMoviesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Recommender.RecommendMoviesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Recommender.RecommendMoviesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Recommender.RecommendMoviesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Recommender.RecommendMoviesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Recommender.RecommendMoviesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Recommender.RecommendMoviesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Recommender.RecommendMoviesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Recommender.RecommendMoviesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Recommender.RecommendMoviesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Recommender.RecommendMoviesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Recommender.RecommendMoviesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RecommendMoviesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RecommendMoviesRequest)
        Recommender.RecommendMoviesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Recommender.internal_static_pb_RecommendMoviesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Recommender.internal_static_pb_RecommendMoviesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Recommender.RecommendMoviesRequest.class, Recommender.RecommendMoviesRequest.Builder.class);
      }

      // Construct using Recommender.RecommendMoviesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        referenceMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Recommender.internal_static_pb_RecommendMoviesRequest_descriptor;
      }

      @java.lang.Override
      public Recommender.RecommendMoviesRequest getDefaultInstanceForType() {
        return Recommender.RecommendMoviesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public Recommender.RecommendMoviesRequest build() {
        Recommender.RecommendMoviesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Recommender.RecommendMoviesRequest buildPartial() {
        Recommender.RecommendMoviesRequest result = new Recommender.RecommendMoviesRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          referenceMovies_ = referenceMovies_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.referenceMovies_ = referenceMovies_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Recommender.RecommendMoviesRequest) {
          return mergeFrom((Recommender.RecommendMoviesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Recommender.RecommendMoviesRequest other) {
        if (other == Recommender.RecommendMoviesRequest.getDefaultInstance()) return this;
        if (!other.referenceMovies_.isEmpty()) {
          if (referenceMovies_.isEmpty()) {
            referenceMovies_ = other.referenceMovies_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureReferenceMoviesIsMutable();
            referenceMovies_.addAll(other.referenceMovies_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Recommender.RecommendMoviesRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Recommender.RecommendMoviesRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList referenceMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureReferenceMoviesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          referenceMovies_ = new com.google.protobuf.LazyStringArrayList(referenceMovies_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string reference_movies = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getReferenceMoviesList() {
        return referenceMovies_.getUnmodifiableView();
      }
      /**
       * <code>repeated string reference_movies = 1;</code>
       */
      public int getReferenceMoviesCount() {
        return referenceMovies_.size();
      }
      /**
       * <code>repeated string reference_movies = 1;</code>
       */
      public java.lang.String getReferenceMovies(int index) {
        return referenceMovies_.get(index);
      }
      /**
       * <code>repeated string reference_movies = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReferenceMoviesBytes(int index) {
        return referenceMovies_.getByteString(index);
      }
      /**
       * <code>repeated string reference_movies = 1;</code>
       */
      public Builder setReferenceMovies(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReferenceMoviesIsMutable();
        referenceMovies_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string reference_movies = 1;</code>
       */
      public Builder addReferenceMovies(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReferenceMoviesIsMutable();
        referenceMovies_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string reference_movies = 1;</code>
       */
      public Builder addAllReferenceMovies(
          java.lang.Iterable<java.lang.String> values) {
        ensureReferenceMoviesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, referenceMovies_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string reference_movies = 1;</code>
       */
      public Builder clearReferenceMovies() {
        referenceMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string reference_movies = 1;</code>
       */
      public Builder addReferenceMoviesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureReferenceMoviesIsMutable();
        referenceMovies_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RecommendMoviesRequest)
    }

    // @@protoc_insertion_point(class_scope:RecommendMoviesRequest)
    private static final Recommender.RecommendMoviesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Recommender.RecommendMoviesRequest();
    }

    public static Recommender.RecommendMoviesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecommendMoviesRequest>
        PARSER = new com.google.protobuf.AbstractParser<RecommendMoviesRequest>() {
      @java.lang.Override
      public RecommendMoviesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecommendMoviesRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecommendMoviesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecommendMoviesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Recommender.RecommendMoviesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RecommendMoviesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RecommendMoviesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    java.util.List<java.lang.String>
        getRecommendedMoviesList();
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    int getRecommendedMoviesCount();
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    java.lang.String getRecommendedMovies(int index);
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    com.google.protobuf.ByteString
        getRecommendedMoviesBytes(int index);
  }
  /**
   * Protobuf type {@code RecommendMoviesResponse}
   */
  public  static final class RecommendMoviesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RecommendMoviesResponse)
      RecommendMoviesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecommendMoviesResponse.newBuilder() to construct.
    private RecommendMoviesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecommendMoviesResponse() {
      recommendedMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecommendMoviesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                recommendedMovies_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              recommendedMovies_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          recommendedMovies_ = recommendedMovies_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Recommender.internal_static_pb_RecommendMoviesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Recommender.internal_static_pb_RecommendMoviesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Recommender.RecommendMoviesResponse.class, Recommender.RecommendMoviesResponse.Builder.class);
    }

    public static final int RECOMMENDED_MOVIES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList recommendedMovies_;
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRecommendedMoviesList() {
      return recommendedMovies_;
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public int getRecommendedMoviesCount() {
      return recommendedMovies_.size();
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public java.lang.String getRecommendedMovies(int index) {
      return recommendedMovies_.get(index);
    }
    /**
     * <code>repeated string recommended_movies = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRecommendedMoviesBytes(int index) {
      return recommendedMovies_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < recommendedMovies_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, recommendedMovies_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < recommendedMovies_.size(); i++) {
          dataSize += computeStringSizeNoTag(recommendedMovies_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRecommendedMoviesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Recommender.RecommendMoviesResponse)) {
        return super.equals(obj);
      }
      Recommender.RecommendMoviesResponse other = (Recommender.RecommendMoviesResponse) obj;

      boolean result = true;
      result = result && getRecommendedMoviesList()
          .equals(other.getRecommendedMoviesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRecommendedMoviesCount() > 0) {
        hash = (37 * hash) + RECOMMENDED_MOVIES_FIELD_NUMBER;
        hash = (53 * hash) + getRecommendedMoviesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Recommender.RecommendMoviesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Recommender.RecommendMoviesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Recommender.RecommendMoviesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Recommender.RecommendMoviesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Recommender.RecommendMoviesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Recommender.RecommendMoviesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Recommender.RecommendMoviesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Recommender.RecommendMoviesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Recommender.RecommendMoviesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Recommender.RecommendMoviesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Recommender.RecommendMoviesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Recommender.RecommendMoviesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Recommender.RecommendMoviesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RecommendMoviesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RecommendMoviesResponse)
        Recommender.RecommendMoviesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Recommender.internal_static_pb_RecommendMoviesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Recommender.internal_static_pb_RecommendMoviesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Recommender.RecommendMoviesResponse.class, Recommender.RecommendMoviesResponse.Builder.class);
      }

      // Construct using Recommender.RecommendMoviesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        recommendedMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Recommender.internal_static_pb_RecommendMoviesResponse_descriptor;
      }

      @java.lang.Override
      public Recommender.RecommendMoviesResponse getDefaultInstanceForType() {
        return Recommender.RecommendMoviesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public Recommender.RecommendMoviesResponse build() {
        Recommender.RecommendMoviesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Recommender.RecommendMoviesResponse buildPartial() {
        Recommender.RecommendMoviesResponse result = new Recommender.RecommendMoviesResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          recommendedMovies_ = recommendedMovies_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.recommendedMovies_ = recommendedMovies_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Recommender.RecommendMoviesResponse) {
          return mergeFrom((Recommender.RecommendMoviesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Recommender.RecommendMoviesResponse other) {
        if (other == Recommender.RecommendMoviesResponse.getDefaultInstance()) return this;
        if (!other.recommendedMovies_.isEmpty()) {
          if (recommendedMovies_.isEmpty()) {
            recommendedMovies_ = other.recommendedMovies_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecommendedMoviesIsMutable();
            recommendedMovies_.addAll(other.recommendedMovies_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Recommender.RecommendMoviesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Recommender.RecommendMoviesResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList recommendedMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRecommendedMoviesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          recommendedMovies_ = new com.google.protobuf.LazyStringArrayList(recommendedMovies_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string recommended_movies = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRecommendedMoviesList() {
        return recommendedMovies_.getUnmodifiableView();
      }
      /**
       * <code>repeated string recommended_movies = 1;</code>
       */
      public int getRecommendedMoviesCount() {
        return recommendedMovies_.size();
      }
      /**
       * <code>repeated string recommended_movies = 1;</code>
       */
      public java.lang.String getRecommendedMovies(int index) {
        return recommendedMovies_.get(index);
      }
      /**
       * <code>repeated string recommended_movies = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRecommendedMoviesBytes(int index) {
        return recommendedMovies_.getByteString(index);
      }
      /**
       * <code>repeated string recommended_movies = 1;</code>
       */
      public Builder setRecommendedMovies(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRecommendedMoviesIsMutable();
        recommendedMovies_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string recommended_movies = 1;</code>
       */
      public Builder addRecommendedMovies(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRecommendedMoviesIsMutable();
        recommendedMovies_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string recommended_movies = 1;</code>
       */
      public Builder addAllRecommendedMovies(
          java.lang.Iterable<java.lang.String> values) {
        ensureRecommendedMoviesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recommendedMovies_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string recommended_movies = 1;</code>
       */
      public Builder clearRecommendedMovies() {
        recommendedMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string recommended_movies = 1;</code>
       */
      public Builder addRecommendedMoviesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRecommendedMoviesIsMutable();
        recommendedMovies_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RecommendMoviesResponse)
    }

    // @@protoc_insertion_point(class_scope:RecommendMoviesResponse)
    private static final Recommender.RecommendMoviesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Recommender.RecommendMoviesResponse();
    }

    public static Recommender.RecommendMoviesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecommendMoviesResponse>
        PARSER = new com.google.protobuf.AbstractParser<RecommendMoviesResponse>() {
      @java.lang.Override
      public RecommendMoviesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecommendMoviesResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecommendMoviesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecommendMoviesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Recommender.RecommendMoviesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_RecommendMoviesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_RecommendMoviesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_RecommendMoviesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_RecommendMoviesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024pb/recommender.proto\022\002pb\"2\n\026RecommendM" +
      "oviesRequest\022\030\n\020reference_movies\030\001 \003(\t\"5" +
      "\n\027RecommendMoviesResponse\022\032\n\022recommended" +
      "_movies\030\001 \003(\t2_\n\020MovieRecommender\022K\n\020rec" +
      "ommend_movies\022\032.RecommendMoviesReques" +
      "t\032\033.RecommendMoviesResponseB\004\n\002pbb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_RecommendMoviesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_RecommendMoviesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_RecommendMoviesRequest_descriptor,
        new java.lang.String[] { "ReferenceMovies", });
    internal_static_pb_RecommendMoviesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_RecommendMoviesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_RecommendMoviesResponse_descriptor,
        new java.lang.String[] { "RecommendedMovies", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
