// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/recommender.proto

package edu.beuth.movies.services.recommender.pb;

/**
 * Protobuf type {@code pb.RecommendMoviesRequest}
 */
public  final class RecommendMoviesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.RecommendMoviesRequest)
    RecommendMoviesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecommendMoviesRequest.newBuilder() to construct.
  private RecommendMoviesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecommendMoviesRequest() {
    referenceMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RecommendMoviesRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              referenceMovies_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            referenceMovies_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        referenceMovies_ = referenceMovies_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.beuth.movies.services.recommender.pb.Recommender.internal_static_pb_RecommendMoviesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.beuth.movies.services.recommender.pb.Recommender.internal_static_pb_RecommendMoviesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest.class, edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest.Builder.class);
  }

  public static final int REFERENCE_MOVIES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList referenceMovies_;
  /**
   * <code>repeated string reference_movies = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getReferenceMoviesList() {
    return referenceMovies_;
  }
  /**
   * <code>repeated string reference_movies = 1;</code>
   */
  public int getReferenceMoviesCount() {
    return referenceMovies_.size();
  }
  /**
   * <code>repeated string reference_movies = 1;</code>
   */
  public java.lang.String getReferenceMovies(int index) {
    return referenceMovies_.get(index);
  }
  /**
   * <code>repeated string reference_movies = 1;</code>
   */
  public com.google.protobuf.ByteString
      getReferenceMoviesBytes(int index) {
    return referenceMovies_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < referenceMovies_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, referenceMovies_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < referenceMovies_.size(); i++) {
        dataSize += computeStringSizeNoTag(referenceMovies_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReferenceMoviesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest)) {
      return super.equals(obj);
    }
    edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest other = (edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest) obj;

    boolean result = true;
    result = result && getReferenceMoviesList()
        .equals(other.getReferenceMoviesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getReferenceMoviesCount() > 0) {
      hash = (37 * hash) + REFERENCE_MOVIES_FIELD_NUMBER;
      hash = (53 * hash) + getReferenceMoviesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.RecommendMoviesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.RecommendMoviesRequest)
      edu.beuth.movies.services.recommender.pb.RecommendMoviesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.beuth.movies.services.recommender.pb.Recommender.internal_static_pb_RecommendMoviesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.beuth.movies.services.recommender.pb.Recommender.internal_static_pb_RecommendMoviesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest.class, edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest.Builder.class);
    }

    // Construct using edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      referenceMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.beuth.movies.services.recommender.pb.Recommender.internal_static_pb_RecommendMoviesRequest_descriptor;
    }

    @java.lang.Override
    public edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest getDefaultInstanceForType() {
      return edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest build() {
      edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest buildPartial() {
      edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest result = new edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        referenceMovies_ = referenceMovies_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.referenceMovies_ = referenceMovies_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest) {
        return mergeFrom((edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest other) {
      if (other == edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest.getDefaultInstance()) return this;
      if (!other.referenceMovies_.isEmpty()) {
        if (referenceMovies_.isEmpty()) {
          referenceMovies_ = other.referenceMovies_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureReferenceMoviesIsMutable();
          referenceMovies_.addAll(other.referenceMovies_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList referenceMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureReferenceMoviesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        referenceMovies_ = new com.google.protobuf.LazyStringArrayList(referenceMovies_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getReferenceMoviesList() {
      return referenceMovies_.getUnmodifiableView();
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public int getReferenceMoviesCount() {
      return referenceMovies_.size();
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public java.lang.String getReferenceMovies(int index) {
      return referenceMovies_.get(index);
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReferenceMoviesBytes(int index) {
      return referenceMovies_.getByteString(index);
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public Builder setReferenceMovies(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReferenceMoviesIsMutable();
      referenceMovies_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public Builder addReferenceMovies(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReferenceMoviesIsMutable();
      referenceMovies_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public Builder addAllReferenceMovies(
        java.lang.Iterable<java.lang.String> values) {
      ensureReferenceMoviesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, referenceMovies_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public Builder clearReferenceMovies() {
      referenceMovies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reference_movies = 1;</code>
     */
    public Builder addReferenceMoviesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureReferenceMoviesIsMutable();
      referenceMovies_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.RecommendMoviesRequest)
  }

  // @@protoc_insertion_point(class_scope:pb.RecommendMoviesRequest)
  private static final edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest();
  }

  public static edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecommendMoviesRequest>
      PARSER = new com.google.protobuf.AbstractParser<RecommendMoviesRequest>() {
    @java.lang.Override
    public RecommendMoviesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RecommendMoviesRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RecommendMoviesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecommendMoviesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.beuth.movies.services.recommender.pb.RecommendMoviesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

